# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_first_name', models.CharField(max_length=30)),
                ('aa_last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicAdvisorResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.IntegerField()),
                ('help_rating', models.IntegerField()),
                ('suggestions', models.CharField(max_length=150)),
                ('academic_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AcademicAdvisor')),
            ],
        ),
        migrations.CreateModel(
            name='CareerAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_first_name', models.CharField(max_length=30)),
                ('ca_last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CareerAdvisorResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.IntegerField()),
                ('help_rating', models.IntegerField()),
                ('suggestions', models.CharField(max_length=150)),
                ('career_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CareerAdvisor')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFullTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give_back', models.CharField(max_length=30)),
                ('my_choice', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FullTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offers_received', models.IntegerField(blank=True, null=True)),
                ('date_accepted', models.DateField()),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('position_title', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=1)),
                ('time_looking', models.IntegerField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('position_description', models.CharField(max_length=30)),
                ('accepted_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('how_obtained', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('internship_flag', models.BooleanField()),
                ('additional_comments', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonInternship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_looking', models.IntegerField(blank=True, null=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Internship')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('academic_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AcademicAdvisor')),
                ('career_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CareerAdvisor')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_introduction', models.CharField(max_length=30)),
                ('mism_decision', models.CharField(max_length=30)),
                ('again', models.CharField(max_length=10)),
                ('again_response', models.CharField(blank=True, max_length=150, null=True)),
                ('additional_classes', models.CharField(blank=True, max_length=150, null=True)),
                ('valuable_class', models.CharField(blank=True, max_length=30, null=True)),
                ('valuable_class_response', models.CharField(blank=True, max_length=150, null=True)),
                ('best_response', models.CharField(blank=True, max_length=150, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=150, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('additional_comments', models.CharField(blank=True, max_length=150, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Person')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Program')),
            ],
        ),
        migrations.AddField(
            model_name='fulltime',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Person'),
        ),
        migrations.AddField(
            model_name='donation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Person'),
        ),
        migrations.AddField(
            model_name='companyfulltime',
            name='full_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.FullTime'),
        ),
    ]
