# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fulltime',
            old_name='time_looking',
            new_name='ft_time_looking',
        ),
        migrations.RemoveField(
            model_name='academicadvisorresponse',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='academicadvisorresponse',
            name='help_rating',
        ),
        migrations.RemoveField(
            model_name='academicadvisorresponse',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='careeradvisorresponse',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='careeradvisorresponse',
            name='help_rating',
        ),
        migrations.RemoveField(
            model_name='careeradvisorresponse',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='fulltime',
            name='salary',
        ),
        migrations.AddField(
            model_name='academicadvisorresponse',
            name='aa_appointment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicadvisorresponse',
            name='aa_help_rating',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AddField(
            model_name='academicadvisorresponse',
            name='aa_suggestions',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='careeradvisorresponse',
            name='ca_appointment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careeradvisorresponse',
            name='ca_help_rating',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AddField(
            model_name='careeradvisorresponse',
            name='ca_suggestions',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fulltime',
            name='ft_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='programresponse',
            name='least_valuable_class',
            field=models.CharField(blank=True, choices=[('415', 'IS 415 (Capstone)'), ('531', 'IS 531 (Enterprise Infrastructure)'), ('550/552', 'IS 550/552 (Capstone)'), ('551', 'IS 551 (Leading Change)'), ('555', 'IS 555 (BI)'), ('560', 'IS 560 (Security)'), ('562', 'IS 562 (Project Management)'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='programresponse',
            name='least_valuable_class_response',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='academicadvisor',
            name='aa_first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='academicadvisor',
            name='aa_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='careeradvisor',
            name='ca_first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='careeradvisor',
            name='ca_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='give_back',
            field=models.CharField(blank=True, choices=[('Money', 'Money (donations to department, scholarship funds, etc.)'), ('Time', 'Time (mentorship, guest lectures, etc.)'), ('Both', 'Both'), ('No', "I don't plan on giving back")], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='my_choice',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='contact',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='date_accepted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='offers_received',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('No Offer', 'I have not received an offer yet.'), ('Not Accepted Yet', 'I received an offer(s), but have not yet accepted.')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='position_description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='position_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(blank=True, choices=[('MISM', 'MISM'), ('BSIS', 'BSIS')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='programresponse',
            name='again',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('NS', 'Not Sure')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='programresponse',
            name='mism_decision',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='programresponse',
            name='program_introduction',
            field=models.CharField(blank=True, choices=[('1', 'Student in the program'), ('2', 'Family member'), ('3', 'Alumni'), ('4', 'School counselor'), ('5', 'Online'), ('6', 'Advertisement'), ('7', 'Information Session'), ('8', 'IS 201'), ('9', 'Other')], max_length=30, null=True),
        ),
    ]
