# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170331_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='companyfulltime',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyfulltime',
            name='full_time',
        ),
        migrations.DeleteModel(
            name='CompanyFullTime',
        ),
    ]
