# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170331_1551'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([('name', 'city', 'state')]),
        ),
    ]
