# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170425_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='position_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='intern_offer',
            field=models.BooleanField(default=False),
        ),
    ]
