# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170426_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Program'),
        ),
    ]
