# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170502_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.AcademicAdvisor'),
        ),
        migrations.AddField(
            model_name='user',
            name='career_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.CareerAdvisor'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(blank=True, choices=[('BSIS', 'BSIS'), ('I-MISM', 'Integrated MISM'), ('N-MISM', 'Non-Integrated MISM')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.CharField(blank=True, choices=[('BSIS', 'BSIS'), ('I-MISM', 'Integrated MISM'), ('N-MISM', 'Non-Integrated MISM')], max_length=30, null=True),
        ),
    ]
