# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170502_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graduationDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
