# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170503_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alumni',
            field=models.BooleanField(default=True),
        ),
    ]
